version: "3"

services:

  http_bin:
    image: python:alpine3.11
    working_dir: /var/www
    command: python server.py
    ports:
    - 8080:8080
    volumes:
      - ./src/test/resources:/var/www

  sftp:
    image: atmoz/sftp:alpine
    command: foo:pass:999

  minio:
    image: bitnami/minio:2021.6.17-debian-10-r60
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minio.rule=Host(`minio`)"
    - "traefik.http.routers.minio.entrypoints=minio_api"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=rootroot
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=rootroot
      - MINIO_DEFAULT_BUCKETS=djobi
      - BITNAMI_DEBUG=true


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.elasticsearch.rule=Host(`elasticsearch`)"
    - "traefik.http.routers.elasticsearch.entrypoints=es"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - ES_JAVA_OPTS=-Xms512m -Xmx512m -Dmapper.allow_dots_in_name=true

volumes:
  minio_data:
    driver: local