version: "3"

services:

  sftp:
    image: atmoz/sftp:alpine
    command: foo:pass:999

  minio:
    image: bitnami/minio:2021.6.17-debian-10-r60
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=rootroot
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=rootroot
      - MINIO_DEFAULT_BUCKETS=djobi
      - BITNAMI_DEBUG=true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - ES_JAVA_OPTS=-Xms512m -Xmx512m -Dmapper.allow_dots_in_name=true