executor:
  type: spark
  spec:
    cluster:
      type: local
    driver:
      cpu: 1
      memory: 4Gb
    workers:
      num: 2
      cpus: 2
      memory: 10Gb
parameters:
  date:
    type: daily_date
jobs:
  job1:
    stages:
    - name: setup_file
      kind: fs-input
      spec:
        path: "./json_1"
        format: json
    - name: as_table
      kind: org.spark.mutate
      spec:
        alias_table: my_json_1
    - name: input
      kind: sql
      check: false
      spec:
        query: "queries/job.sql"
    - name: filter
      kind: "org.spark.mutate"
      spec:
        adds:
          day: "{{day}}\\/{{month}}\\/{{year}}"
    - name: output
      kind: org.elasticsearch.output
      spec:
        host: "{{env.elasticsearch}}"
        index: "out"
        clean_query: "day:{{day}}\\/{{month}}\\/{{year}}"
