FROM elasticsearch:2.4

RUN wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/delete-by-query/2.4.6/delete-by-query-2.4.6.zip && \
    /usr/share/elasticsearch/bin/plugin install file:./delete-by-query-2.4.6.zip